# A human-readable name for the workflow
name: CI Build and Push

# This section defines the trigger for the workflow.
# It will run on every push to the "main" branch.
on:
  push:
    branches: [ "main" ]

# This section defines the jobs to be run.
jobs:
  build-and-push-image:
    # The job will run on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest
    
    # These are the sequential steps the job will perform
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      # It uses the secrets we created earlier
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build the Docker image and push it to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # The path to the directory containing the Dockerfile
          context: ./app
          # Tells the action to push the image after building
          push: true
          # The name and tag for the image on Docker Hub
          # FORMAT: <YourDockerHubUsername>/<ImageName>:<Tag>
          tags: abhayr110801/hello-app:latest # <--- CHANGE THIS USERNAME IF IT'S DIFFERENT