name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    # Use a specific, compatible OS version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-app:${{ github.sha }}

  deploy-to-kubernetes:
    needs: build-and-push-image
    # Use the same specific, compatible OS version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes (minikube)
        uses: manusa/actions-setup-minikube@v2.9.0
        with:
          minikube version: 'v1.32.0'
          kubernetes version: 'v1.28.3'
          
      - name: Deploy to Minikube using Helm
        run: |
          helm upgrade --install hello-release ./hello-app-chart \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/hello-app \
            --set image.tag=${{ github.sha }}